# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('papierbackup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 22, 6, 21, 10, 310387, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
