# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20160502_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ManyToManyField(to='documents.Category'),
        ),
    ]
