# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20160508_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime',
            field=models.CharField(default='application/octet-stream', max_length=255),
            preserve_default=False,
        ),
    ]
