# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_file_mime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mime',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
