# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20160522_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='mime',
        ),
    ]
