# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_file_mime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['modification_date', 'creation_date']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['creation_date']},
        ),
    ]
