# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', "0009_auto_20160524_2004"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-modification_date', '-creation_date']},
        ),
    ]
